# As of 9-12-17, Amazon ECS CLI supports Docker compose file syntax versions
# 1 and 2
# (see: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html)
version: '2'

services:

  elasticsearch:
    # *Note: We are using Elasticsearch version 2.x because django-haystack,
    # one of our dependencies, only supports Elasticsearch versions
    # 1.x and 2.x, not the newer versions (as of 8/7/17). See:
    # http://django-haystack.readthedocs.io/en/v2.6.0/installing_search_engines.html#elasticsearch
    #
    # Also, we are using Elasticsearch v2.3 (even though v2.4.6 is
    # available) because it is the highest version that AWS supports of the
    # 2.x major version (as of 8/7/17). The logic here is that we want the
    # local deployment to mirror our deployment on AWS. See:
    # https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg.html
    image: elasticsearch:2.3

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docker_adage
      - POSTGRES_PASSWORD=password123

  core:
    image: adage-server/docker-backend
    build: .
    container_name: adage-django
    environment:
      - DOCKER_DEV=true
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - core
    volumes:
      - ./nginx/dev/adage-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./interface/bin:/home/static
