version: 2
jobs:
  tests:
    docker:
      # Primary docker container where the tests will be run
      - image: ubuntu:18.04

      # Secondary docker container for database service
      - image: postgres:9.5.14
        environment:
          POSTGRES_USER: root

      # Secondary docker container for Elasticsearch service
      - image: elasticsearch:2.4.6

    working_directory: ~/adage-server

    steps:
      - checkout
      - run:
          name: get_pseudomonas
          working_directory: ~/
          command: |
            apt update && apt upgrade -y
            apt install git mercurial -y
            hg clone --config ui.tls=false https://bitbucket.org/greenelab/get_pseudomonas
            ln -s ~/get_pseudomonas/gen_spreadsheets.py ~/
            ln -s ~/get_pseudomonas/get_pseudo_sdrf.py  ~/
      - run:
          name: backend tests
          working_directory: ~/adage-server/adage
          command: |
            apt install postgresql-client python-pip -y
            createuser -h localhost --superuser ubuntu
            createdb -h localhost circleci_test
            pip install -r requirements.txt
            python manage.py test
      - run:
          name: frontend tests
          working_directory: ~/adage-server/interface
          command: |
            apt install node.js npm libfontconfig -y
            npm -g install grunt-cli karma-cli bower npm
            apt purge npm && hash -r
            npm install
            bower install --allow-root
            grunt
            grunt test

workflows:
  version: 2
  test:
    jobs:
      - tests
