version: 2
jobs:
  tests:
    machine: true

    steps:
      - checkout
      #- run: hg clone https://bitbucket.org/greenelab/get_pseudomonas
      #- run: ln -s get_pseudomonas/gen_spreadsheets.py .
      #- run: ln -s get_pseudomonas/get_pseudo_sdrf.py  .
      #- run: cd ~/adage-server
      #- run: pip install -r adage/requirements.txt
      #- run: python adage/manage.py test adage

workflows:
  version: 2
  test:
    jobs:
      - tests
